sudo: required
dist: trusty
language: csharp
mono: none
dotnet: 1.0.1
solution: Com.Moonlay.Service.Auth.sln
services:
    - docker

before_install:
    - dotnet restore ./Com.Moonlay.Service.Auth.sln
    - dotnet publish ./Com.Moonlay.Service.Auth.WebApi/Com.Moonlay.Service.Auth.WebApi.csproj -o ./bin/publish
    - docker build -f ./Dockerfile.travis -t moonlay/com-moonlay-service-auth-webapi:$TRAVIS_BUILD_NUMBER .
install: true

#before_script:
#    - dotnet build ./Com.Moonlay.Service.Auth.sln
script:
    - dotnet test Com.Moonlay.Service.Auth.WebApi.Test/Com.Moonlay.Service.Auth.WebApi.Test.csproj

after_success:
    - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push moonlay/com-moonlay-service-auth-webapi:$TRAVIS_BUILD_NUMBER;
      fi    