FROM microsoft/aspnetcore-build:1.1
WORKDIR /app

COPY Com.Moonlay.Service.Project.WebApi/*.csproj .
RUN dotnet restore

COPY Com.Moonlay.Service.Project.WebApi/. .
RUN dotnet publish --output /out/ --configuration Release