version: '3'
 
services:
  moonlay-service-project-webapi-test:
    image: com-moonlay-service-project-webapi:test
    environment:
      - ASPNETCORE_ENVIRONMENT=Test
      - DefaultConnection=Server=mssql,1433;Database=com.moonlay.db.project;User=sa;password=Standar123;MultipleActiveResultSets=true 
      - Authority=https://auth.moonlay.com
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - mssql

  mssql:
    image: microsoft/mssql-server-linux:2017-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Standar123
      - MSSQL_PID=Developer
    ports:
      - "1401:1433"