version: '3'
 
services:

  mssql:
    image: microsoft/mssql-server-linux:2017-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Standar123.
      - MSSQL_PID=Developer
    ports:
      - "1401:1433"