version: '3'
 
services:
  moonlay-service-auth-webapi:
    image: moonlay/com-moonlay-service-auth-webapi
    environment:
      - DefaultConnection=Server=mssql.auth;Database=com.moonlay.auth;User=sa;Password=Admin-pwd;MultipleActiveResultSets=true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    links:
      - mssql.auth

  mssql.auth:
    image: microsoft/mssql-server-linux
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Admin-pwd
      - MSSQL_PID=Developer
    expose:
      - "1433"