version: '3'

services:
  com.moonlay.service.project.webapi:
    image: com.moonlay.service.project.webapi
    build:
      context: ./Com.Moonlay.Service.Project.WebApi
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DefaultConnection=Server=mssql;Database=com.moonlay.db.project;User=sa;password=Standar123;MultipleActiveResultSets=true
      - Authority=http://127.0.0.1:5000
    ports:
      - "5001:80"
    depends_on:    
      - moonlay-service-auth-webapi-test
      - mssql
    links:
      - moonlay-service-auth-webapi-test:auth-provider
      - mssql

  moonlay-service-auth-webapi-test:
    image: moonlay/com-moonlay-service-auth-webapi:37
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DefaultConnection=Server=mssql,1433;Database=com.moonlay.db.auth;User=sa;password=Standar123;MultipleActiveResultSets=true
    ports:
      - "5000:80"
    depends_on:
      - mssql
    links:
      - mssql 

  mssql:
    image: microsoft/mssql-server-linux
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Standar123
      - MSSQL_PID=Developer
    ports:
      - "1401:1433"