FROM microsoft/aspnetcore-build:2.0.2-stretch
WORKDIR /app

COPY Com.Moonlay.Service.Project.WebApi/*.csproj .
RUN dotnet restore

COPY Com.Moonlay.Service.Project.WebApi/. .
RUN dotnet publish --output /out/ --configuration Release